# Generated by Django 5.1.15 on 2026-05-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blank_names_remove_logincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='видимое имя'),
        ),
    ]
