# Generated by Django 5.1.15 on 2026-05-20 03:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchRoom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='название комнаты')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('playback_position', models.FloatField(default=0.0, verbose_name='позиция, с')),
                ('is_playing', models.BooleanField(default=False, verbose_name='воспроизводится')),
                ('state_updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='состояние обновлено')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL, verbose_name='ведущий')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='videos.video', verbose_name='видео')),
            ],
            options={
                'verbose_name': 'комната просмотра',
                'verbose_name_plural': 'комнаты просмотра',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('guest_label', models.CharField(blank=True, max_length=80, verbose_name='имя гостя')),
                ('role', models.CharField(choices=[('host', 'Ведущий'), ('viewer', 'Зритель')], default='viewer', max_length=10, verbose_name='роль')),
                ('is_online', models.BooleanField(default=False, verbose_name='онлайн')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='подключился')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='отключился')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='rooms.watchroom')),
            ],
            options={
                'verbose_name': 'участник комнаты',
                'verbose_name_plural': 'участники комнаты',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('room', 'user'), name='uniq_room_user')],
            },
        ),
    ]
