# Generated by Django 5.1.15 on 2026-05-20 03:19

import django.db.models.deletion
import uuid
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('file', models.FileField(upload_to=videos.models.video_upload_path, verbose_name='файл')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=videos.models.thumbnail_upload_path, verbose_name='превью')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='длительность, с')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='размер, байт')),
                ('content_type', models.CharField(default='video/mp4', max_length=100, verbose_name='MIME-тип')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
                ('is_public', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'видео',
                'ordering': ('-created_at',),
            },
        ),
    ]
